version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: basicapi
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - ":3306"
    networks:
      - custom-network
    volumes:
      - mysql_data:/var/lib/mysql
  springbootapp:
    container_name: spring_boot_app
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/basicapi
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - custom-network
volumes:
  mysql_data: {}
networks:
  custom-network:
    driver: bridge

